### ISSUE TITLE
45176  (Cleveland Crib) - No data 

### ISSUE THREAD

**Issue by kknee** [glos/myglos#10]
Ed working with Guan

**Comment by kknee** [comment]
From Guan: "I don't have 45169 and 45176 in the system, although they both have folders on FTP with couple files in it. It doesn't look like they are operational in terms of data transfer. Otherwise, I should have seen files packed up there."

**Comment by kkoch** [comment]
From @everhamme "We will send Guan a separate email with the metadata for 45176 and 45169. Both have some basic info on greatlakesbuoys.org." Is transmitting and showing values on NDBC. Still not showing up in our portal 7/13.

**Comment by everhamme** [comment]
Greg C should have sent or is sending this information . Both buoys are on greatlakesbuoys.org

**Comment by kkoch** [comment]
45176b is in obs cache. Guan having issues because obs explorer cannot handle that 45176 and 45176b are both at same location. Portal does not appear to have an issue with same location (both buoy id's show) but even though GN obs link is in place, 45176b (bottom/sonde) does not show data.  Not sure if this is the obs issue manifesting itself there. Suggestion for the  > Would a possible fix work to change the location of one of the buoys by one degree for either lat or lon in obs?

**Comment by kkoch** [comment]
all is good

**Comment by kkoch** [comment]
Before vacation on 8/26 we were seeing data for the bottom sonde in portal.  Now we are not.  Not sure if it is a problem on our end, or on data provider's.

**Comment by kkoch** [comment]
Needed to remove 45176b from geonetwork since I see we are pulling in parameters as one buoy (as it should be).
