### ISSUE TITLE
Add Grand River Conservation Authority data to GLOS portal

### ISSUE THREAD

**Issue by kknee** [glos/myglos#100]
Contact = Bryan McIntosh

From Bryan:

This just became very easy for us both. We use the exact same REST service types as Lake Simcoe.

- GRCA (CSV same as Simcoe): http://kiwis.grandriver.ca/KiWIS/KiWIS?datasource=0&service=kisters&type=queryServices&request=getStationList&format=csv 

 
 
On that note, I see you are requesting CSV from their REST endpoint. Since the company that makes the software is German based, they use semicolons as the divider, not commas. However, if you want you can change the Lake Simcoe (and ours) to use commas.
 

- GRCA (using comma delimiter): [http://kiwis.grandriver.ca/KiWIS/KiWIS?datasource=0&service=kisters&type=queryServices&request=getStationList&format=csv&csvdiv=,](http://kiwis.grandriver.ca/KiWIS/KiWIS?datasource=0&service=kisters&type=queryServices&request=getStationList&format=csv&csvdiv=,) 
- Lake simcoe (using comma delimiter): http://www.lsmaps.ca/KiWIS/KiWIS?service=kisters&type=queryServices&request=getStationList&datasource=0&format=csv&csvdiv=,&station_no=%s

**Comment by lukecampbell** [comment]
Is this for the old portal or MyGLOS?

**Comment by kknee** [comment]
It is for The Glos Portal: http://portal.glos.us/

@cgalvarino needs to get the data flowing and then this task will transition to you.

**Comment by cgalvarino** [comment]
@kknee, I need a bit more info before I can add these.  I'll email you.

**Comment by kknee** [comment]
We're waiting on metadata from the data provider.  @kkoch can you follow up?

**Comment by kkoch** [comment]
I have the metadata form (received last week from Bryan) and will be working on updating GN today.

**Comment by kkoch** [comment]
Initial GN record is in place.  Have gone back to GRIN and asking them to provide QAQC details.  I am assuming this will be a Luke manually curated dataset so did not add in a link other than for the info URL or variables. But GLOS keywords are there for you to pull. http://data.glos.us/metadata/srv/eng/main.home?uuid=522af949-054f-4252-b0ff-98979ef90c59

In addition, they do list some use contraints. I don't know if there is any impact on this for our use. https://data.grandriver.ca/about-licensing.html

**Comment by kkoch** [comment]
GN record is complete.  Passing back to @cgalvarino to get into portal (obs) and then can do the circular thing in GN for variables/parameters.

**Comment by cgalvarino** [comment]
I'm not sure I need to do anything.  If you see dots in the obs cache (old portal), my work is done.  That appears to be the case.

![image](https://cloud.githubusercontent.com/assets/180985/25448554/d0a6d64a-2a86-11e7-850e-f6c045dbadb3.png)

**Comment by kkoch** [comment]
Need to have a DMAC discussion on how to handle this.  I believe @lukecampbell we need to add this as a collection similar to co-ops, ndbc, etc?  Next steps?  I can add a single "GR Cons Auth" GN record (actually already created as noted above) and/or can be manually curated or I can add all stations as individual records.

If needed obs data is at > 
http://data.glos.us/portal/getObsCatalog.php?providers=glos,kistersCsv

**Comment by Bobfrat** [comment]
@kkoch do you have an abstract for the collection in general? 
For example, NDBC collection has the following:

_The National Data Buoy Center (NDBC) is a part of the National Oceanic and Atmospheric Administration's (NOAA) National Weather Service (NWS). NDBC designs, develops, operates, and maintains a network of data collecting buoys and coastal stations._

**Comment by kkoch** [comment]
@Bobfrat As noted above, all info is in the GeoNetwork metadata record > http://data.glos.us/metadata/srv/eng/main.home?uuid=522af949-054f-4252-b0ff-98979ef90c59

**Comment by Bobfrat** [comment]
This data is on dev now. Note the title doesn't match that of the metadata record because we'd have 2 entries, so let me know if you'd like to title changed from Grand River Conservation Authority

<img width="1438" alt="screen shot 2017-10-19 at 3 43 01 pm" src="https://user-images.githubusercontent.com/5702672/31790696-5204d34e-b4e4-11e7-91e3-61ae63e16bb5.png">

**Comment by kkoch** [comment]
I've pulled off the 'glos categories' and 'variables' from the GN record which I think would be the hook that shows the 'old' information since we no longer need that record to show in portal... so once that rolls thru I don't think we would have two records.  So yes, the title of your collection should also be "Grand River Information Network".  You also need to make sure it shows under the hydrologic category.  

Also need have the links for data access going to the GN metadata record as well as Grand River, so : https://data.grandriver.ca (with the text of "Grand River Information Network" and then the metadata link would be http://data.glos.us/metadata?uuid=522af949-054f-4252-b0ff-98979ef90c59 

Also the Abstract you have is the old one.  You might not have caught the changed record in GN.  It should be > The Grand River Conservation Authority (GRCA) monitors stream flow, water quality and meteorological data in the Grand River (Ontario). This up-to-the-minute information is vital to our important role of forecasting floods and issuing flood warnings. Data is also used to monitor water quality at automated water quality stations at key locations. This information helps the GRCA, municipalities and others understand water quality trends and the impact of human activities on the health of the river system.

**Comment by Bobfrat** [comment]
@kkoch I've made those changes on dev.

**Comment by kkoch** [comment]
Looks good to me but passing to @tslawecki for decision on push to production.

**Comment by kknee** [comment]
@kkoch @tslawecki any update?  Can we release?

**Comment by tslawecki** [comment]
This looks great now that I finally looked at it ... release!

________________________________

**Comment by kknee** [comment]
@Bobfrat we're good to release this

**Comment by Bobfrat** [comment]
Ok great. We have a couple other updates on dev that aren't on production. They include https://github.com/glos/myglos/issues/168, https://github.com/glos/myglos/issues/169, https://github.com/glos/myglos/issues/104. If those are ok, I'd prefer to make one release that includes them all

**Comment by tslawecki** [comment]
I'm good with #168, perhaps Colin should approve 104 and 169?



________________________________

**Comment by kknee** [comment]
@Bobfrat noticed one issue when testing this on production.  We're filtering the markers based on zoom level for the TOC, but not for the search results, so when you add Grand River to the map, it seems like it didn't add all the stations until you zoom in:

![image](https://user-images.githubusercontent.com/196868/32912787-1cb955f6-cade-11e7-95ff-dc7f6cacd1a3.png)
 vs. 

![image](https://user-images.githubusercontent.com/196868/32912791-279ce19a-cade-11e7-95b0-e9d0c6154a31.png)

**Comment by kkoch** [comment]
Closing this.  I think the zoom is fine at present. We can revisit later if we decide otherwise.
