### ISSUE TITLE
Evaporation stations (glenijc) - dual feeds in portal

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#112]
We are seeing two hits in the Portal.  Assume one is now an active NDBC feed, the other is from our own GN.  GN is not showing any results.  Seems like in theory we would like to have the GN one as the active record (this is the one titled "Lake Michigan Evaporation and Meteorological Data from....).  If there isn't a way to do that, I will disable the GN records.

IDs : WSLM4, SRLM4

![image](https://cloud.githubusercontent.com/assets/6392982/25044997/dce28c76-20f7-11e7-9aa9-87cf7d14d47b.png)

NOTE: GRIM4 is working just fine. Getting feed results with just one GN hit.

**Comment by kknee** [comment]
@kkoch there is no data in the obs feed for this station, which is why we are showing no results: http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Station+WSLM4+-+White+Shoal%2C+MI

**Comment by kkoch** [comment]
Yes. Thus my submitting as an issue.  Should have clarified that. 
a) we need to get to obs
b) we need to disable NDBC feed

**Comment by kknee** [comment]
got it.  @gcutrell let us know if you need help looking at the obs issue. We'll suppress the NCBC feed once we have an alternative up and running

**Comment by gcutrell** [comment]
@kknee @kkoch I just checked but we don't have any station platform obs for any of the evaporation stations. I believe @tslawecki decided using the NDBC feed was the easiest way to get data into the portal since the GLEN stations directly send data to NDBC via's GLERL's comm network. I think we would need to push the NDBC feed into GLOS's xml incoming obs directory and configure station platforms for each GLEN station so the incoming data would be parsed and placed in the glos_obs database.

**Comment by kkoch** [comment]
I am removing the links from GeoNetwork will leave the (very nice IMHO) metadata there but of course with getting the NDBC feed only we lose that connection to the metadata from the portal.
