### ISSUE TITLE
ESF3 (and other ESF buoys) not reporting

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#122]
It was brought to my attention at IAGLR that ESF3 (and potentially other ESF buoys) 'should' be showing up in the portal but are not.  Before I go back to the PI to verify that they are submitting correctly, would someone just check the FTP folder and make sure it hasn't gone into the wrong folder or see if the data is there but with errors?

Then if the data is not there, I will go back to the PI and make sure they aren't submitting it to the wrong ftp address.

**Comment by gcutrell** [comment]
@kkoch The only stations that are retrieving data in their ftp directory is ESF4 and ESF7 (which are working on the protal). Directories for ESF1, 2, 3, and 5 have not received data since 11/11/2016 and 11/12/2016. My guess is the their programs ftp has not been enabled or maybe they are sending data to glos.us, but I don't know if that would have worked in November.

**Comment by kkoch** [comment]
ESF3 reporting. Sent email to ESF so assuming other buoys are just not transmitting at this time.
