### ISSUE TITLE
45170 data not in obs cache (but is being ftp'd)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#124]
45170 (Illinois-Indiana Sea Grant) is showing data from NDBC but not through our obs cache. Can we verify that we should be getting data from PI and see if it is an issue on our end or it they are no longer submitting to our ftp folder?

**Comment by kkoch** [comment]
Sent email to Jay Beugly jbeugly@purdue.edu asking if he is pushing the data.

His response: _Thanks for letting us know, I think there was a problem on Greatlakesbuoys too. Everything seemed fine on our site. I have cc’d those who might have a better handle on how the data might be pushed. Hopefully we can all sort it out quickly. Jay_

**Comment by gcutrell** [comment]
@kkoch GLOS is receiving the data because I can view it in their ftp directory. The issue is I couldn't find the platform ID setup for 45170. Guan also didn't recall setting up a platform ID for 45170. So I need to create a new platform for 45170.  The confusing part is how there was data in thredds even though Guans script was not setup to ingest 45170. @kknee  Where is thredds pulling the buoy data from?

**Comment by kknee** [comment]
@cheryldmorse did we end up pulling live data from the obs DB directly or 52NSOS?

**Comment by cheryldmorse** [comment]
The data is coming directly from the obs database. There already is a table in the db for station 45170.

**Comment by kkoch** [comment]
Here is the original issue for when this was set up in case that helps >https://github.com/glos/myglos/issues/67

**Comment by kkoch** [comment]
Looking good - seeing data now. @gcutrell can you document what the issue was? I closed the ticket.
