### ISSUE TITLE
In External Links, change "Data Access" title to "Metadata"

### ISSUE THREAD

**Issue by kknee** [glos/myglos#14]

**Comment by kkoch** [comment]
Correction (addition) to this issue.  I see that it was changed for external links on catalog page. Also needs to be changed on map page from "Data Source" to "Metadata".  (I also don't think it needs the word 'record' following metadata.)

**Comment by kknee** [comment]
@kkoch where do you still see "Data Source", I see "Metadata Record" everywhere.

**Comment by kkoch** [comment]
Click on buoy that we don't have data for and it will show the external links (which actually I'd like to also see on buoys that we have data for, but that's another request needing) > e.g., 45176 Cleveland Crib Buoy.  This is on map view.

**Comment by kkoch** [comment]
Just thought I'd show a specific example since above example is not valid.  Buoy where we are getting active data shows "metadata record" as requested.  Buoy that has been decommissioned but is still ours, has GN link but no data feed so shows 'data source' instead.

![metadatarecord](https://cloud.githubusercontent.com/assets/6392982/18596588/e149b878-7c17-11e6-8c79-7fe79bf64170.PNG)

Another good example is pulling up a searched item like the Maumee River tracker.  Still says Data Source as well.

**Comment by kknee** [comment]
fixed
