### ISSUE TITLE
Buoy color for ndbc buoys (two stations not the same color icon)

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#163]
Wondering why buoy markers act this way -

I add a buoy to the map where data is not quite current and it shows up as a blue-purple.  A buoy with current data is more of a red-purple.  Okay makes sense to have a difference.  However, as soon as I search for something else, it changes the not-so-current buoy to a transparent-purple (which makes even more sense - I like the transparency).   I'm just wondering why it doesn't show transparent right away?  If I look at all the NDBC buoys at once, the non-current ones are transparent.  It only seems to do this if I'm searching one by one.

1) With just two buoys > Added GRIM4 first (Lake Sup) to map.  Then added SRLM4 over on Lake Huron (at this point is a blue-purple)
![image](https://user-images.githubusercontent.com/6392982/29790903-30482e62-8c09-11e7-9b2d-a39892f393fc.png)

2) If I do a search for another buoy, SRLM4 changes to a transparent purple  (which is more what I would expect and like if it is because of the data).  
![image](https://user-images.githubusercontent.com/6392982/29791137-ecdf0316-8c09-11e7-93aa-40936e79e06b.png)

Just seems odd that it starts out a non-standard solid color and then goes transparent-ish. And only if I search for something else.

Any way we can force the transparency right off the bat?

**Comment by kkoch** [comment]
Note that the issue apparently does not have to do with whether there is data available or not, as today they are both transmitting data but show different colors of purple.

![image](https://user-images.githubusercontent.com/6392982/31733868-e37ae712-b40a-11e7-832f-ebaf9b19fae1.png)

**Comment by kknee** [comment]
@Bobfrat the issue here is that srlm4, when added to the map, is transparent.  Transparency normally indicates no recent data, but that's not the case for srlm4.  Any thoughts on why it's transparent when added to the map?  @gitchrisadams FYI in case this is something you can track down easily.

**Comment by gitchrisadams** [comment]
This problem is due to a preview marker being set to blue.
So whenever you search it previews the marker and displays like this for wslm4 for example:
![image](https://user-images.githubusercontent.com/9978238/32611606-1844530e-c534-11e7-9bc3-132dd3c14ba3.png)

If you add that marker to the map, and the marker is transparent, the blue preview marker shows through the transparency and displays like this:
![image](https://user-images.githubusercontent.com/9978238/32611679-42ed3b3e-c534-11e7-9d56-1f8e301cce58.png)

When you close the search box, the preview marker is no longer display and the marker shows as the normal color like this:
![image](https://user-images.githubusercontent.com/9978238/32611750-6b4f8d98-c534-11e7-9a16-9e0f71a3857a.png)

I attempted to remove the preview marker when new marker is added, as well as changing the color of the preview marker on add, but this was not working properly and getting very complicated with the marker layers nested in Layer Groups and how the markers and subviews are setup. I ran this by @Bobfrat and we wanted to post the problem/what we found here to see how much more time we should invest in troubleshooting this issue.

@kknee

**Comment by kknee** [comment]
@gitchrisadams  - see my last comment above.  The behavior that you report above is indeed expected, but the issue was that the marker was transparent even tho it had recent data.  That no longer seems to be the case - of the four buoys listed above:

SLRM4 has recent data and is opaque
STDM4 has recent data and is opaque
WSLM4 does not have recent data and is transparent
grim4 does not have recent data and is transparent

@kkoch can you reproduce the issue with any other buoy?

**Comment by kkoch** [comment]
It is only this station.  I have not seen it with any other.

**Comment by kknee** [comment]
This station being WSLM4?  In that case I think we can close this.  That station is correctly transparent.

**Comment by kkoch** [comment]
Too late in the season to test. I will try to put this on my radar in the spring when all are active and see if things are normal or need attention.
