### ISSUE TITLE
"Data matures like wine, applications like fish"

### ISSUE THREAD

**Issue by tslawecki** [glos/myglos#200]
Almost totally off topic, ran across while here so am sharing ...

*In my last post touching on my case for Data Engineers, my friend Greg Rahn provided a humorous quote about data from Andy Todd:*

*“Data matures like wine, applications like fish”*

  .
  .
  .

*In this post, though, I’d like to address some of the humor behind the quote — the implication that data gets better as it ages, while applications get worse (and start to smell like stinky fish).*

-- From http://www.oraclemusings.com/?p=250

Also see https://www.toolbox.com/blogs/dukeganote/data-matures-like-wine-applications-like-fish-030118

**Comment by kkoch** [comment]
I particularly like this statement: "There’s a balance to be struck in keeping data fresh and usable — it doesn’t just get better with age, but rather needs to be continually assessed against **use cases** in order to keep it useful."

I'm sure the relevance of which could be discussed in our analytics discussions.

**Comment by kkoch** [comment]
Closing.  :)
