### ISSUE TITLE
MTRI Satelite products not showing correct bounding boxes (was: MTRI switch to weekly zip (April 15))

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#207]
Action items May 1

- [ ] @ColinNBrooks "poke" to do his tasks to make the weekly vs. full load take effect

- [x] @kknee (RPS) to turn back on MTRI updates

- [ ] test to be sure portal (OWS) is behaving

**Comment by ColinNBrooks** [comment]
Thanks; let's touch base around April 15th on this.

**Comment by ColinNBrooks** [comment]
I'm somebody now, I can have issues assigned to me!

**Comment by ColinNBrooks** [comment]
We have started producing the MTRI remote sensing products again, and will now be posting them as a weekly file, rather than a cumulative file. Here's more information for MTRI researcher Karl Bossee, who creates these water color products:

"The first set of CPA-A products were shared with GLOS this week via ftp for their portal. This includes 3-4 dates for each lake (more dates for the surface temperature product), looking back as far as the beginning of April for clear images. The data are also available on our network such that the WMS should pull them to the portal.

"I have modified our protocol such that the files shared via ftp will only contain updated images, rather than the full set of products each time. I will maintain an archive of shared files in case any updates are missed.

Please let me know if there are any issues pulling this new data or with how it displays on the portal. If not, more data will be sent next week."

To see what products should now be accessible to & through the GLOS Portal, please take a look at the MTRI page for 2018 products at: http://www.greatlakesremotesensing.org/

**Comment by kknee** [comment]
@cheryldmorse can you turn this process back on test the weekly files?

**Comment by cheryldmorse** [comment]
All set

**Comment by kknee** [comment]
thanks @cheryldmorse!

@kkoch can you keep an eye on this and close when you are satisfied?

**Comment by kkoch** [comment]
Is this an error in oceansmap and/or mtri data (vs. known/expected behavior)? 
Added CHL to lake michigan and temp to lake erie, then created virtual buoy in erie.  Seemed odd for two or three things, one that it showed the michigan data on the erie buoy and two showed invalid date for the temp; also reads 'no results for this time period' on the graph results.  I don't know if the mixed lake situation has always been there and I just didn't try it before, but the time period seems off to me for sure, especially because it shows a temperature value.  The same thing but in reverse happens when I put a virtual buoy in lake mich.

![image](https://user-images.githubusercontent.com/6392982/40121951-b0cd9ad6-58f0-11e8-8f63-332fdcae470f.png)

![image](https://user-images.githubusercontent.com/6392982/40122134-1d05caa2-58f1-11e8-8a44-83c389c075fb.png)

**Comment by kkoch** [comment]
Also if I just stick to a single lake, I get the invalid date and no results on graphing.

**Comment by ColinNBrooks** [comment]
It's not what I would expect to happen from a user perspective, at least.

I recreated what you did, and one thing I noticed is that the bounding boxes for each lake are quite large (see below). Could the virtual buoy tool be trying to query for values within those bounding boxes for the satellite data? You can see that Lake Michigan, for example, overlaps with western Lake Erie, and Lake Erie overlaps with the southern 2/3 of Lake Michigan and over half of Lake Ontario.

I'm not sure of the origin of the bounding boxes. I'd be surprised if its a result of the geospatial outputs we create, but perhaps that is the cause?

![image](https://user-images.githubusercontent.com/20344813/40123110-68fc6a4a-58f3-11e8-9bee-1f8589ad7141.png)

**Comment by kkoch** [comment]
@Bobfrat can you dig into this on the OceansMap side of things?  From MTRI (@ColinNBrooks et. al) >

- It looks like we have a few datasets (e.g. NCI, LST) that have images with bounding boxes that are not uniform and tight that could be causing this problem. I'm not sure how the GLOS data portal ingests the extent data- I was assuming that the extents are pulled from those advertised in our WMS GetCapabilities  call, but I've edited our WMS metadata file so that the advertised extents are tighter and it looks like the changes aren't showing on the portal. Perhaps there's some manual step that needs to take place to re-ingest those extents?

Note the following image where I've selected Lake Erie so the blue bounding box is going way over Lake Michigan.
![image](https://user-images.githubusercontent.com/6392982/40365299-378dda62-5da2-11e8-910c-0d6d55b1921b.png)

**Comment by Bobfrat** [comment]
Because we are grouping the MTRI layers, we are doing a superset of the bounding boxes found in each layer (CDOM, Chlorophyl, Doc, Natural Color Imagery etc). For this particular Lake Erie issue it looks like Natural Color Imagery is the offending BBox in the GetCaps:

```
nci_erie
(-91.0, 39.0, -77.0, 45.0)
```

**Comment by kkoch** [comment]
Okay Mike @ MTRI (thanks @ColinNBrooks ) fixed the bounding boxes so we aren't getting duplicate buoys.  HOWEVER> still seeing invalid date error >  Note that I have a virtual buoy in Lake Mich.  I see a data value (.15 ug/L) in the pop-up but it states invalid date there and if you look at the graph there is no data and also "no results found for this time period".

![image](https://user-images.githubusercontent.com/6392982/40439556-437d86aa-5e89-11e8-9bda-30a9ad46c785.png)

**Comment by kkoch** [comment]
Fixed by MTRI.
