### ISSUE TITLE
MTRI layers issue

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#229]
@tslawecki having an issue in Chrome where the layers were throwing an error when trying to load MTRI satellite data for Lake Erie > "Error drawing this layer". I was not able to replicate - tested using FF, IE, Chrome on both Win7 & Win10.  But if others could test as well, that would be great.

HOWEVER, while testing I did discover that Lake Mich is cutting off the top of the layer for cdom, doc, kd490, photic, suspended minerals; while the other layers (CHL, temperature, imagery) look okay.  So wondering if there is an issue with the data coming in?

![image](https://user-images.githubusercontent.com/6392982/41420356-392945dc-6fc2-11e8-9327-df86b2c54908.png)

**Comment by kknee** [comment]
@ColinNBrooks seeming the same result on http://www.greatlakesremotesensing.org/ so I think this is on the MTRI side.

**Comment by tslawecki** [comment]
I'm pleased to report that the initial issue with MTRI LE satellite layers not displaying on my computer went away after an unrelated reboot ...

**Comment by ColinNBrooks** [comment]
Looks like it's just a factor of the June 5th image we used to create the data - that's where the data cuts off. Older data don't have this issue. Will confirm with data processors too.

**Comment by kkoch** [comment]
@ColinNBrooks I notice this is still happening

**Comment by ColinNBrooks** [comment]
My colleague Karl Bosse that creates most of this output confirmed that this is just an artefact of the June 5th MODIS image; specifically, he said:
"Yes, the lake was caught between MODIS images which is why the top of Lake Michigan is cut off."

The only new outputs since then for Lake Michigan are lake surface temperature raster layers & they aren't cut off there.

I would just chalk this up to being at the mercy of the satellite gods & this is all they saw that day.

**Comment by kkoch** [comment]
...or goddesses <grin>. Closing
