### ISSUE TITLE
Implement QARTOD for HABS

### ISSUE THREAD

**Issue by kknee** [glos/myglos#46]
couple moving pieces here:
- [ ] @tslawecki & LT to develop test parameters
- [ ] @cheryldmorse to insert QC variables into netCDF files
- [ ] @lukecampbell to implement QARTOD scripts

**Comment by tslawecki** [comment]
An additional moving piece is what we do with the QC variables once we have them. A few notions as a starting point, let's discuss ... tomorrow's call? Next week?
1. Provide indication of how many points in a displayed time series have non-zero QC flags.
2. Add (optional) shading to chart to show where potentially "severe" or "minor" QC issues may be present. "Severe" and "Minor" to be defined.
3. Add (optional) filtering to chart to show QC by either censoring data with "severe" or "minor" QC issues or by changing symbolization (transparency or color change)
-

**Comment by kkoch** [comment]
Per discussion at DMAC mtg > Dissolved Oxygen numbers were failing (due to them actually being DO% and issues with incorrect variables). Luke strongly suggests we get the metadata correct even where it would minimally pass some inspection. Tad will have Greg look at and at a minimum take care of issues where the variable names have spaces (should be lowercase and use underscores for spacing (e.g., Dissolved Oxygen vs. dissolved_oxygen)). Once we figure out what needs to be changed, a script can be run to correct back files.  Thredds will need to be restarted afterwards. Luke also wants us to be sure and track which files have been modified.

**Comment by kkoch** [comment]
Luke to apply Tad's numbers to the data and visually inspect.  To be done this budget year if possible (before end of Oct.)

**Comment by tslawecki** [comment]
@lukecampbell - do you now have credentials/edit access to THREDDS, or is this still blocking?

**Comment by lukecampbell** [comment]
We need to figure out a way to create a read/write mount. Right now the THREDDS mount for the data is read-only, which is fine. But, wherever we process the data we need to be able to write to the datasets. The old approach was to generate netCDF files and transfer them to the host using `scp` but doing that continuously for QARTOD would result in a lot of additional labor and would very likely bog down the internal network due to all of the network I/O

**Comment by tslawecki** [comment]
Luke, is this a blocking issue or can we proceed for now with scp? I will talk to Guan about his configuration of the NFS server unless you already know what you want to change.

**Comment by kknee** [comment]
Status Update:
1. we are successfully performing basic QARTOD on all HABS datasets in test environment
2. we are working on installing and automating QARTOD processing on process1.glos.us

**Comment by lukecampbell** [comment]
We worked around the NFS issue because of time constraints. Ben's got an approach worked out where we make local changes to the files and use [`scp`](https://en.wikipedia.org/wiki/Secure_copy) to shuttle the files to the storage server.

We had it kind of ready to go but the last round of testing revealed that:
1. Some of the files had inconsistent variables names (now fixed)
2. If something went wrong while performing qartod, it wouldn't clean up correctly (actively working on)
3. Lacked physical access to GLOS internal network (fixed)
4. Lacked adequate permissions or credentials for GLOS internal network (fixed)

**Comment by kknee** [comment]
@lukecampbell can this be closed?

**Comment by lukecampbell** [comment]
Yes
