### ISSUE TITLE
Add MOE-49 (LOBOviz - new buoys for GLOS)

### ISSUE THREAD

**Issue by kknee** [glos/myglos#75]
From Tad:
It's SOS 1.0.0, but the service request returns a .tsv file for download (?).
http://ontario2.loboviz.com/cgi-ioos/GetCapabilities

**Comment by kknee** [comment]
From Luke:

I don't see that happening in the scale of 1-day. Off the cuff estimates are several days for integrating SOS sources.
- [ ] Add new harvest source [LT]
- [x] Create and compile metadata for the source [LT] 
- [ ] Link the geonetwork metadata record with the harvested dataset in oceansmap [RPS]
- [ ] Address any data quality issues [TBD]
- [ ] Deploy to dev [RPS]
- [ ] Test dev [RPS]
- [ ] Deploy to Production [RPS]

**Comment by kkoch** [comment]
Due to the bi-national nature, would be really good if we could get this done this year even though the buoys will be out of the water Nov. 15.  Since it is unlikely ASA will be able to fit this in by end of October, Kathy will email them and ask them to fill out a metadata form and let them know we are working on it.

**Comment by kkoch** [comment]
Emailed John telling him we will be working on this and asking someone from his organization to fill out my metadata form (one form per buoy).

**Comment by kkoch** [comment]
Here is full text of John's original email to Tad so we have it captured here for integration > 

From: Thibeau, John (MOECC) John.Thibeau@ontario.ca
Sent: Wednesday, October 12, 2016 1:40 PM
To: Tad Slawecki
Subject: FW: SOS interface for LOBOviz 

Hi Tad,
Sorry this took so long.

We’ve deployed our new buoy system in the central basin of Lake Erie. It’s also been included here with the two Lake Ontario systems we were discussing back in Feb 2016.

John Thibeau
Crew Chief

Ontario Ministry of the Environment and Climate Change
Great Lakes Field Operations
t.: (416) 235-6530

From: John Andrea [mailto:john.andrea@satlantic.com] 
Sent: August 12, 2016 1:03 PM
To: Thibeau, John (MOECC)
Subject: Re: SOS interface for LOBOviz

Hi John,

I'm finished with this interface setup. You'll need to register the sites to get them included with the data collection service.
   Again, SCCF has built a good reference for the interface at their site:
http://recon.sccf.org/sos/

http://ontario.loboviz.com/cgi-ioos/GetCapabilities?request=GetCapabilities&service=SOS&sections=ServiceProvider

http://ontario2.loboviz.com/cgi-ioos/GetCapabilities?request=GetCapabilities&service=SOS&sections=ServiceProvider

http://ontario3.loboviz.com/cgi-ioos/GetCapabilities?request=GetCapabilities&service=SOS&sections=ServiceProvider

I've used "MoE" as the provider identifier.
You can see the site numeric identifiers by making a plot then "Permalink" and looking at the URL.

http://ontario2.loboviz.com/cgi-ioos/DescribeSensor?request=DescribeSensor&service=SOS&version=1.0.0&procedure=urn:ioos:station:MOE:49

http://ontario2.loboviz.com/cgi-ioos/GetObservation?request=GetObservation&service=SOS%25version=1.0.0&offering=urn:ioos:station:MOE:49&observedproperty=water_temperature

Some of the parameter names have changed since the setup for SCCF, but the parameter names are available in the "Describe" mode.

John

**Comment by kkoch** [comment]
John had a question on metadata.  He is working on that part and will get back to us.

**Comment by kkoch** [comment]
New person assigned for metadata (details below).  He will send me the metadata for the first of 4 buoys shortly and we can then determine what our next steps need to be.  Buoys to be implemented for the season soon.

Ryan Mototsune
Crew Chief, Great Lakes Field Operations
Ontario Ministry of the Environment and Climate Change
Environmental Monitoring and Reporting Branch
125 Resources Road
Toronto, ON M9P 3V6
Office: (416) 235-6367  
Cell: (647) 618-5687

**Comment by kkoch** [comment]
Metadata has been added at this point as a single record. GN record is > http://data.glos.us/metadata/srv/eng/main.home?uuid=7d8d48b6-a6d9-4f5e-9dd9-75028cd55f4b

Next steps?  Believe that Dan Rusinski @limnotech has been working on getting these into thredds.  If we are handling these like other buoys, they'll need to get to obs and then I'll need to create separate GN records with the correct linkages.

**Comment by kknee** [comment]
@kkoch if we want to handle like other sources, they need to get into obs DB first and then into THREDDS.  @cgalvarino and @cheryldmorse have handled many 3rd-party sources for us let us know if/when you need us to jump in.

**Comment by kkoch** [comment]
Received additional updates to metadata from Ryan.  He also noted that Western Lake Ontario 1 buoy has stopped communicating with servers so data is not being updated on the website real-time (and he does not have an ETA for when this will be resolved).

**Comment by kkoch** [comment]
Buoys are reporting in Data Portal.  

However @gcutrell notes that another issue is glos_obs doesn't parse blue-green-algae or chlorophyll with units other than rfu. I believe RFU is only used by one sensor manufacturer. The omoecc stations are reporting in ug/L (or ppb) so blue-green-algae or chlorophyll will not go into glos obs.

Turbidity is also an issue.  It seems we will need to gather a list of new tags/observations to add to glos_obs. I know Ed acknowledged GLOS is lacking current data and it seems we need more universal tag names. For example the MOECC guy is going to say (yes he did :) )the sonde is not a YSI but it’s the only way to currently read in turbidity (ntu).  

I am closing this original ticket and creating a new one for the above obs/parameter topic.
