### ISSUE TITLE
GLCFS netddf files posted

### ISSUE THREAD

**Issue by kkoch** [glos/myglos#89]
Hi Tad, DMAC

I've posted the 2016 GLCFS 50-day (301-350) netcdf files:
http://www.glerl.noaa.gov/emf/glcfs/tmp/forTad/

There are 17 files, totaling 5.6 GB.

Also,
I've posted the GLCFS 16-day (351-366) netcdf files:
http://www.glerl.noaa.gov/emf/glcfs/tmp/forTad/

There are 17 files, totaling 1.8 GB.

These 34 files would replace the 2016 6-hr nowcast-2d, nowcast-3d, and nowcast-forcing files for doys 301-350, and for 351-366.

For example:
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/ncfmrc-2d/files/catalog.html
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/ncfmrc-3d/files/catalog.html
http://tds.glos.us/thredds/catalog/glos/glcfs/archivecurrent/michigan/nowcast-forcing-fmrc-2d/files/catalog.html

Let me know if you have any questions or difficulty downloading the 
files.  And please let me know when you've grabbed all of of them so 
that I can delete then from our server.

Thanks,
Greg

-- 
Gregory A. Lang
NOAA/Great Lakes Environmental Research Lab
4840 South State Rd.
Ann Arbor, MI 48108-9719
(734) 741-2250
http://www.glerl.noaa.gov

**Comment by gcutrell** [comment]
Spoke with Guan on 1/3/2017 about the details to complete this action. The notes from our conversation are in [https://github.com/glos/glos_server_script/blob/master/glcfs/README.md]. As of now I don't have a username/password for GLOS storage to complete this task, so it has yet to be done.

Guan mentioned he never wrote a code to automate this task because it only comes up a few times a year and it would be difficult to do without potential errors occurring.

**Comment by gcutrell** [comment]
Gregory Lang's files have been archived and old 2016 Nowcast files have been removed.
