### ISSUE TITLE
45169  (Cleveland Wind)  - No Data

### ISSUE THREAD

**Issue by kknee** [glos/myglos#9]
Ed working with Guan

**Comment by kknee** [comment]
from Guan: "I don't have 45169 and 45176 in the system, although they both have folders on FTP with couple files in it. It doesn't look like they are operational in terms of data transfer. Otherwise, I should have seen files packed up there."

**Comment by kkoch** [comment]
From @everhamme "We will send Guan a separate email with the metadata for 45176 and 45169.  Both have some basic info on greatlakesbuoys.org."  Is transmitting and showing values on NDBC. Still not showing up in our portal 7/13.

**Comment by tslawecki** [comment]
45169 still not displayable in http://portal.glos.us

**Comment by tslawecki** [comment]
Oops. Pay more attention to the prompts!

**Comment by kknee** [comment]
still no link to the obs cache in GN, which explains why it's not in the portal.

**Comment by kkoch** [comment]
Rather circular but it is not linked in GN because there is no link for me to put from cache.  Tad's last message states "is" in postgres (and Guan can see it on ObsExplorer). I checked that as well and agree that it is odd that it is not showing via cache.

Based on the title in the database I extrapolated the following URL, but that doesn't work (just shows [ ] on the webpage > http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Cleveland+Wind+Buoy+-+Cleveland%2C+OH

**Comment by kkoch** [comment]
Got it I think.  I noticed that the Crib buoy has the ? in the title that looks odd but works. So I replaced wind for the crib > http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Cleveland+Wind+Buoy+%3F+Cleveland%2C+OH  

I'm testing by putting that url into GN

**Comment by kkoch** [comment]
In postgres database but does not display the ndbc ID (which is why I wasn't finding it in obs cache) – I think it needs to be entered into the ‘other ID’ field or possibly update the station_url with the ndbc link?

Platform URL is correct > http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Cleveland+Wind+Buoy+%3F+Cleveland%2C+OH

I’ve put this in GN with the variables. It has populated through to the portal although I had to tweak some of the variables so that should show up the next push.
